# Docker image config
image:
  repository: <your-dockerhub-username>/myapp
  tag: latest
  pullPolicy: IfNotPresent

# Secret values (Base64 encoding handled by Helm)
secrets:
  DB_USERNAME: "admin"
  DB_PASSWORD: "s3cr3tPass"

# Service settings
service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
