apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
